# @timeout 120
POST http://213.170.70.30:4321/run
Content-Type: application/json

{
  "serviceName": "{{serviceName}}",
  "token": "{{token}}",
  "branch": "case-1",
  "ratePerSecond": 11,
  "testCount": 1200,
  "onPremises": true
}