### КЕЙС 2: Тест для аккаунта acc-5
POST http://localhost:1234/test/run
Content-Type: application/json

{
  "serviceName": "{{serviceName}}",
  "token": "{{token}}",
  "ratePerSecond": 2,
  "testCount": 100,
  "processingTimeMillis": 60000
}

### Stop running test to save time and resources
POST http://localhost:1234/test/stop/{{serviceName}}