global:
  scrape_interval: 10s
  scrape_timeout: 5s

scrape_configs:
  - job_name: 'spring'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['bombardier:1234']
  - job_name: 'spring-external'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:1234']