global:
  scrape_interval: 10s
  scrape_timeout: 5s

scrape_configs:
  - job_name: 'bombardier-docker-network-job'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['bombardier:1234']
  - job_name: 'bombardier-host-job'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:1234']
  - job_name: 'online-store-job'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8081']
  - job_name: 'online-shop-job'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:18081']