### КЕЙС 3: Тест для аккаунта acc-5 (увеличенная нагрузка)
### ⚠️  ВАЖНО: ПЕРЕД ЗАПУСКОМ ТЕСТА ЗАПУСТИТЕ ПРИЛОЖЕНИЕ С АККАУНТОМ acc-5:
### export PAYMENT_ACCOUNTS=acc-5 && mvn spring-boot:run

POST http://localhost:1234/test/run
Content-Type: application/json

{
  "serviceName": "{{serviceName}}",
  "token": "{{token}}",
  "ratePerSecond": 2,
  "testCount": 500,
  "processingTimeMillis": 60000
}

### Stop running test to save time and resources
POST http://localhost:1234/test/stop/{{serviceName}}